name: eocout_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  carousel_slider_plus: ^6.0.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  dio: ^5.4.3+1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.1+2
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  path_provider: ^2.1.3
  pinput: ^5.0.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.3.0
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - .env
  fonts:
    - family: Poppins
      fonts:
        # THIN
        - asset: fonts/Poppins-Thin.ttf
          weight: 100

        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        # EXTRA LIGHT
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200

        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        # LIGHT
        - asset: fonts/Poppins-Light.ttf
          weight: 300

        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        # REGULAR
        - asset: fonts/Poppins-Regular.ttf
          weight: 400

        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic

        # MEDIUM
        - asset: fonts/Poppins-Medium.ttf
          weight: 500

        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        # SEMI BOLD
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        # BOLD
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        # EXTRA BOLD
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800

        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        # BLACK
        - asset: fonts/Poppins-Black.ttf
          weight: 900

        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
