// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpmf_sXUggfJqmwvteF4qeRDOP-SHyeM',
    appId: '1:1095787047782:web:19e1774ba2d350cfcb36a7',
    messagingSenderId: '1095787047782',
    projectId: 'eocout-a82f7',
    authDomain: 'eocout-a82f7.firebaseapp.com',
    storageBucket: 'eocout-a82f7.appspot.com',
    measurementId: 'G-XWH31M0J5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzAyclQhSO43yDTMGwZQjjcvD0VI_mB0',
    appId: '1:1095787047782:android:c022e1072b14f111cb36a7',
    messagingSenderId: '1095787047782',
    projectId: 'eocout-a82f7',
    storageBucket: 'eocout-a82f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjUyrZdfxy_0rjpsitkER7ik3ab5s1tSY',
    appId: '1:1095787047782:ios:e916d2ae3e4a5252cb36a7',
    messagingSenderId: '1095787047782',
    projectId: 'eocout-a82f7',
    storageBucket: 'eocout-a82f7.appspot.com',
    iosBundleId: 'com.example.eocoutFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjUyrZdfxy_0rjpsitkER7ik3ab5s1tSY',
    appId: '1:1095787047782:ios:e916d2ae3e4a5252cb36a7',
    messagingSenderId: '1095787047782',
    projectId: 'eocout-a82f7',
    storageBucket: 'eocout-a82f7.appspot.com',
    iosBundleId: 'com.example.eocoutFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVpmf_sXUggfJqmwvteF4qeRDOP-SHyeM',
    appId: '1:1095787047782:web:049fdc4853728f92cb36a7',
    messagingSenderId: '1095787047782',
    projectId: 'eocout-a82f7',
    authDomain: 'eocout-a82f7.firebaseapp.com',
    storageBucket: 'eocout-a82f7.appspot.com',
    measurementId: 'G-J7EFSTJPK8',
  );
}
