Map<String, List<String>> indonesiaProvince = {
  "Aceh": [
    "Banda Aceh",
    "Langsa",
    "Lhokseumawe",
    "Meulaboh",
    "Sabang",
    "Bireuen",
    "Blangpidie",
    "Calang",
    "Kuala Simpang",
    "Kutacane",
    "Lhoksukon",
    "Sigli",
    "Sinabang",
    "Suka Makmue",
    "Takengon"
  ],
  "Sumatera Utara": [
    "Medan",
    "Binjai",
    "Pematangsiantar",
    "Sibolga",
    "Tanjungbalai",
    "Tebing Tinggi",
    "Padang Sidempuan",
    "Gunungsitoli",
    "Kisaran",
    "Lubuk Pakam",
    "Lima Puluh",
    "Rantau Prapat",
    "Kabanjahe",
    "Balige",
    "Stabat"
  ],
  "Sumatera Barat": [
    "Padang",
    "Bukittinggi",
    "Payakumbuh",
    "Sawahlunto",
    "Solok",
    "Padang Panjang",
    "Pariaman",
    "Batusangkar",
    "Lubuk Basung",
    "Painan",
    "Simpang Empat",
    "Tuapejat",
    "Muara Siberut",
    "Siberut"
  ],
  "Riau": [
    "Pekanbaru",
    "Dumai",
    "Bangkinang",
    "Bengkalis",
    "Rengat",
    "Tembilahan",
    "Pasir Pengaraian",
    "Siak Sri Indrapura",
    "Bagan Siapi-api",
    "Pangkalan Kerinci",
    "Teluk Kuantan"
  ],
  "Kepulauan Riau": [
    "Tanjung Pinang",
    "Batam",
    "Tanjung Balai Karimun",
    "Dabo Singkep",
    "Ranai"
  ],
  "Jambi": [
    "Jambi",
    "Sungai Penuh",
    "Muara Bulian",
    "Muara Bungo",
    "Muara Tebo",
    "Sarolangun",
    "Sengeti",
    "Bangko",
    "Kuala Tungkal",
    "Muara Sabak"
  ],
  "Sumatera Selatan": [
    "Palembang",
    "Lubuklinggau",
    "Pagaralam",
    "Prabumulih",
    "Baturaja",
    "Kayuagung",
    "Lahat",
    "Martapura",
    "Muaradua",
    "Sekayu",
    "Indralaya",
    "Pangkalan Balai"
  ],
  "Kepulauan Bangka Belitung": [
    "Pangkal Pinang",
    "Tanjung Pandan",
    "Mentok",
    "Koba",
    "Manggar",
    "Toboali"
  ],
  "Bengkulu": [
    "Bengkulu",
    "Argamakmur",
    "Curup",
    "Kepahiang",
    "Manna",
    "Mukomuko"
  ],
  "Lampung": [
    "Bandar Lampung",
    "Metro",
    "Kalianda",
    "Sukadana",
    "Gunung Sugih",
    "Liwa",
    "Kotabumi",
    "Krui",
    "Gedong Tataan",
    "Kota Agung",
    "Pringsewu",
    "Mesuji",
    "Tulang Bawang",
    "Menggala",
    "Blambangan Umpu",
    "Simpang Pematang"
  ],
  "Banten": [
    "Serang",
    "Tangerang",
    "Cilegon",
    "Tangerang Selatan",
    "Rangkasbitung",
    "Pandeglang",
    "Tigaraksa",
    "Tangerang Selatan",
    "Maja"
  ],
  "Jawa Barat": [
    "Bandung",
    "Bogor",
    "Depok",
    "Bekasi",
    "Cirebon",
    "Sukabumi",
    "Tasikmalaya",
    "Banjar",
    "Cimahi",
    "Purwakarta",
    "Subang",
    "Sumedang",
    "Majalengka",
    "Indramayu",
    "Karawang",
    "Cianjur",
    "Kuningan",
    "Garut"
  ],
  "Jawa Tengah": [
    "Semarang",
    "Surakarta (Solo)",
    "Magelang",
    "Tegal",
    "Salatiga",
    "Pekalongan",
    "Purwokerto",
    "Cilacap",
    "Pati",
    "Kudus",
    "Blora",
    "Jepara",
    "Kendal",
    "Ungaran",
    "Batang",
    "Brebes",
    "Temanggung",
    "Wonosobo",
    "Boyolali",
    "Klaten",
    "Sragen",
    "Wonogiri",
    "Kebumen",
    "Banyumas"
  ],
  "Jawa Timur": [
    "Surabaya",
    "Malang",
    "Kediri",
    "Blitar",
    "Madiun",
    "Mojokerto",
    "Jombang",
    "Probolinggo",
    "Pasuruan",
    "Sidoarjo",
    "Banyuwangi",
    "Situbondo",
    "Bondowoso",
    "Lumajang",
    "Jember",
    "Tulungagung",
    "Nganjuk",
    "Ngawi",
    "Magetan",
    "Ponorogo",
    "Trenggalek",
    "Pacitan",
    "Bojonegoro",
    "Lamongan",
    "Tuban",
    "Gresik",
    "Bangkalan",
    "Sumenep",
    "Sampang",
    "Pamekasan"
  ],
  "Yogyakarta": [
    "Yogyakarta",
    "Sleman",
    "Bantul",
    "Wonosari",
    "Wates",
  ],
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Jakarta Utara"
  ],
  "Bali": [
    "Denpasar",
    "Singaraja",
    "Tabanan",
    "Gianyar",
    "Amlapura",
    "Bangli",
    "Semarapura",
    "Negara",
    "Mangupura"
  ],
  "Kalimantan Barat": [
    "Pontianak",
    "Singkawang",
    "Mempawah",
    "Sambas",
    "Ketapang",
    "Sanggau",
    "Sintang",
    "Putussibau",
    "Ngabang"
  ],
  "Kalimantan Tengah": [
    "Palangka Raya",
    "Sampit",
    "Pangkalan Bun",
    "Muara Teweh",
    "Puruk Cahu",
    "Kuala Kapuas",
    "Buntok",
    "Kasongan"
  ],
  "Kalimantan Selatan": [
    "Banjarmasin",
    "Banjarbaru",
    "Martapura",
    "Pelaihari",
    "Barabai",
    "Amuntai",
    "Kandangan",
    "Rantau",
    "Marabahan",
    "Tanjung"
  ],
  "Kalimantan Timur": [
    "Samarinda",
    "Balikpapan",
    "Bontang",
    "Tenggarong",
    "Sangatta",
    "Penajam",
    "Tanjung Redeb",
    "Sendawar"
  ],
  "Kalimantan Utara": [
    "Tanjung Selor",
    "Tarakan",
    "Nunukan",
    "Malinau",
    "Sebatik"
  ],
  "Nusa Tenggara Barat": [
    "Mataram",
    "Bima",
    "Sumbawa Besar",
    "Dompu",
    "Taliwang",
    "Gerung",
    "Praya",
    "Selong"
  ],
  "Nusa Tenggara Timur": [
    "Kupang",
    "Maumere",
    "Ende",
    "Labuan Bajo",
    "Ruteng",
    "Bajawa",
    "Waingapu",
    "Waikabubak",
    "Kalabahi",
    "Lewoleba",
    "Atambua",
    "Soe"
  ],
  "Sulawesi Barat": [
    "Mamuju",
    "Polewali",
    "Majene",
    "Mamasa",
    "Pasangkayu",
  ],
  "Sulawesi Selatan": [
    "Makassar",
    "Parepare",
    "Palopo",
    "Bone",
    "Watampone",
    "Bulukumba",
    "Sinjai",
    "Bantaeng",
    "Selayar",
    "Takalar",
    "Gowa",
    "Sungguminasa",
    "Maros",
    "Pangkajene",
    "Barru",
    "Soppeng",
    "Watan Soppeng",
    "Wajo",
    "Sengkang",
    "Sidrap",
    "Pinrang",
    "Enrekang",
    "Tana Toraja",
    "Rantepao",
    "Palopo"
  ],
  "Sulawesi Tenggara": [
    "Kendari",
    "Bau-Bau",
    "Kolaka",
    "Unaaha",
    "Andoolo",
    "Raha",
    "Buranga",
    "Wanggudu",
    "Lasusua"
  ],
  "Sulawesi Tengah": [
    "Palu",
    "Poso",
    "Donggala",
    "Tolitoli",
    "Buol",
    "Luwuk",
    "Morowali",
    "Ampana",
    "Parigi"
  ],
  "Gorontalo": [
    "Gorontalo",
    "Limboto",
    "Tilamuta",
    "Marisa",
    "Kwandang",
  ],
  "Sulawesi Utara": [
    "Manado",
    "Bitung",
    "Tomohon",
    "Manado",
    "Bitung",
    "Tomohon",
    "Kotamobagu",
    "Airmadidi",
    "Tondano",
    "Langowan",
    "Amurang",
    "Tahuna"
  ],
  "Maluku": [
    "Ambon",
    "Tual",
    "Masohi",
    "Dobo",
    "Saumlaki",
    "Bula",
    "Namlea",
    "Piru",
    "Saparua"
  ],
  "Maluku Utara": [
    "Sofifi",
    "Ternate",
    "Tidore",
    "Tobelo",
    "Labuha",
    "Daruba",
    "Maba"
  ],
  "Papua Barat": [
    "Manokwari",
    "Sorong",
    "Fakfak",
    "Kaimana",
    "Raja Ampat",
    "Bintuni",
    "Waisai"
  ],
  "Papua Barat Daya": [
    "Sorong",
    "Fakfak",
    "Kaimana",
  ],
  "Papua Tengah": [
    "Nabire",
    "Timika",
    "Enarotali",
    "Wamena",
    "Sinak",
    "Ilaga",
    "Sugapa",
    "Karubaga"
  ],
  "Papua Pegunungan": [
    "Wamena",
    "Tiom",
    "Elelim",
    "Kenyam",
    "Sumo",
  ],
  "Papua Selatan": [
    "Merauke",
    "Tanah Merah",
    "Mappi",
    "Asmat",
    "Mindiptana",
    "Boven Digoel",
    "Agats"
  ],
  "Papua": [
    "Jayapura",
    "Sentani",
    "Wamena",
    "Abepura",
    "Keerom",
    "Genyem",
    "Sarmi",
    "Bonggo",
    "Arso"
  ],
};

RegExp emailRegex = RegExp(
    r"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?");
